services:

  mariadb:
    image: mariadb:latest
    container_name: symbellibrary_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - symbellibrary_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: symbellibrary_phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  symbellibrary_data:
